# available directory themes:
# spearmint, peppermint, hemingway, brookmint
theme = 'brookmint'

[general]
title = "Bonsai Examples Hub"
logo = ""
iconLogo = "tabler:coffee"

[general.seo]
name = "Bonsai Example Hub"
description = "Example Workflows for the Bonsai-Rx Language"
url = "https://banchan86.github.io/example-hub-minted-directory/"

[directoryData.source]
name = "default"    # default, mock, sheets, json
links = "normal"

[directoryData.tagPages]
title = "{0} Apps"

[directoryData.search]
placeholder = "Search among {0} workflows"

[directory.tagPages]
title = "{0} Frameworks"

[[directoryData.tags]]
key = "neuroscience"
name = "Neuroscience"
color = "blue"
emoji = "👃"
description = "Breathing techniques are a popular feature in meditation apps."

[[directoryData.tags]]
key = "signal"
name = "Signal Processing"
color = "green"
emoji = "💤"
description = "Some apps include music that slowly goes away to help you sleep better and rest."

[header.banner]
show = false
text = "bonsai"
link = "https://bonsai-rx.org/"
brandText = "bonsai"

[header.navbar]
colorModeSelector = true

[[header.navbar.links]]
name = "Install Bonsai"
href = "https://bonsai-rx.org/"
target = "_blank"

[header.actionButton]
text = "Submit a workflow"
href = "https://tally.so"

[footer]
description = "Website for Bonsai workflow examples."

[footer.socials.github]
link = "https://github.com/bonsai-rx"
icon = "tabler:brand-github"

[footer.socials.discord]
link = "https://discord.gg/QcthRPuZnr"
icon = "tabler:brand-discord"