# available directory themes:
# spearmint, peppermint, hemingway, brookmint
theme = 'brookmint'

[general]
<<<<<<< HEAD
title = "Meditation Apps"
=======
title = "Bonsai Examples Hub"
>>>>>>> 798a89d (Modify directory settings.toml to remove unused bits)
logo = ""
iconLogo = "tabler:coffee"

[general.seo]
name = "Bonsai Example Hub"
description = "Example Workflows for the Bonsai-Rx Language"
url = "https://banchan86.github.io/example-hub-minted-directory/"

[directory.data]
source = "default"  # default, mock, sheets, json
links = "default"

[directoryData.tagPages]
title = "{0} Apps"

[directoryData.search]
placeholder = "Search among {0} listings of this directory :)"

[[directoryData.tags]]
key = "breathing"
name = "Breathing"
color = "blue"
emoji = "👃"
description = "Breathing techniques are a popular feature in meditation apps."

[[directoryData.tags]]
key = "sleep"
name = "Sleep"
color = "green"
emoji = "💤"
description = "Some apps include music that slowly goes away to help you sleep better and rest."

[[directoryData.tags]]
key = "meditation"
name = "Meditation"
color = "purple"
emoji = "🧘‍♂️"
description = "A meditation for your life. It's a great way to relax and clear your mind. It's also a great way to improve your sleep."

[[directoryData.tags]]
key = "yoga"
name = "Yoga"
color = "purple"
emoji = "🧘‍♂️"
description = "A yoga for your life."

[[directoryData.tags]]
key = "timer"
name = "Timer"
color = "green"
emoji = "⏰"
description = "Timers can be used to track how much you meditate."

[header.banner]
show = false
text = "bonsai"
link = "https://bonsai-rx.org/"
brandText = "bonsai"

[header.navbar]
colorModeSelector = true

[[header.navbar.links]]
name = "Install Bonsai"
href = "https://bonsai-rx.org/"
target = "_blank"

[header.actionButton]
text = "Submit a workflow"
href = "https://tally.so"

[footer]
description = "Website for Bonsai workflow examples."

[footer.socials.github]
link = "https://github.com/bonsai-rx"
icon = "tabler:brand-github"

[footer.socials.discord]
link = "https://discord.gg/QcthRPuZnr"
icon = "tabler:brand-discord"

[ui.icons]
dark = "tabler:moon"
light = "tabler:sun"
