[general]
title = "Bonsai Examples Hub"
logo = "../../bonsai/template/logo.svg"
iconLogo = "tabler:coffee"

[general.seo]
name = "Bonsai Example Hub"
description = "Example Workflows for the Bonsai-Rx Language"
url = "https://banchan86.github.io/example-hub-minted-directory/"

[directory.data]
source = "default"  # default, mock, sheets, json
links = "default"

# [directory.data.sheets]
# key = "1BKVVFysQT8ZuPY8hUp--jwTrN-U20TrtML0idECIWmc"

# [directory.data.airtable]
# base = "base id"
# table = "Table Name"

[directory.search]
placeholder = "Search among {0} workflows"
showCount = true
icon = "tabler:search"

[directory.search.tags]
display = "show-all" # options: none,select,show-all
intersection = false

[directory.grid]
list = false
type = ""

[directory.grid.emptyState]
text = "Seems that this entry is missing from the archives."
type = "button"                                              # options: button, simple, link
icon = "tabler:exclamation-mark"

[directory.grid.card]
image = true
border = "shadow" # options: dashed, shadow, outline

[directory.grid.submit]
show = true
first = false
title = "Submit a template"
description = "Submit a template to show off a good project to other people."
hideable = true

[directory.featured]
showOnAllPages = true
showOnSide = true
icon = "tabler:star"
labelForCard = "Featured ✨"

[directory.tagPages]
title = "{0} Frameworks"

[[directory.tags]]
key = "code"
name = "Code Based"
color = "blue"

[[directory.tags]]
key = "visual"
name = "Visual Based"
color = "green"

[header.banner]
show = false
text = "bonsai"
link = "https://bonsai-rx.org/"
brandText = "bonsai"

[header.navbar]
colorModeSelector = true

[[header.navbar.links]]
name = "Install Bonsai"
href = "https://bonsai-rx.org/"
target = "_blank"

[header.actionButton]
text = "Submit a workflow"
href = "https://tally.so"

[footer]
description = "Website for Bonsai workflow examples."

[footer.socials.github]
link = "https://github.com/bonsai-rx"
icon = "tabler:brand-github"

[footer.socials.discord]
link = "https://discord.gg/QcthRPuZnr"
icon = "tabler:brand-discord"

[ui.icons]
dark = "tabler:moon"
light = "tabler:sun"